name: Latest Medium blog posts

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with latest Medium blogs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 5
          feed_list: "https://medium.com/feed/@gauravchaudhari_"
          disable_webhook: true
